### ISSUE TITLE
Replicating the behaviour of the plot function applied to spatstat objects

### ISSUE THREAD

**Issue by APoinas** [For-a-few-DPPs-more/spatstat-interface#1]
A lot of objects in spatstat have their own behaviour when you run "plot(name_of_the_object)" but I'm having trouble replicating this behaviour in python. For example, here is a code in R doing a rank envelope test to test if some data is generated from a Poisson PP.

```
library(spatstat)
rho0 = 100
alpha0 = 0.05
S_length = 2
# Generating data from a very repulsive DPP.
S = simulate(dppBessel(lambda=rho0, alpha=alpha0, sigma=0, d=2), 1, W=owin(c(0,S_length), c(0,S_length)))
# Doing an envelope test using Ripley's K function.
Env_test = envelope(S, Kest, nsim=199)
# Plotting the result of the test.
plot(Env_test)
```

The resulting plot is then
![1](https://user-images.githubusercontent.com/58079527/125357629-63be2e00-e357-11eb-823e-da21d6c345a3.png)

But, when I tried to do the same thing with spatstat-interface using the following code:

```
import numpy as np
import pandas as pd

import rpy2.robjects as robjects
from rpy2.robjects import numpy2ri
numpy2ri.activate()

from spatstat_interface.interface import SpatstatInterface
from spatstat_interface.utils import convert_r_df_to_pandas_df

spatstat = SpatstatInterface(update=True)
spatstat.import_package("core", "geom", update=False)

rho = 100
alpha = 0.05
sigma = 0
d = 2
params = {"lambda": rho, "alpha": alpha, "sigma": sigma, "d": d}
my_dpp = spatstat.core.dppBessel(**params)
bound = robjects.FloatVector([0, 2])
window = spatstat.geom.owin(xrange=bound, yrange=bound)
# Generating data from a very repulsive DPP.
rsample = spatstat.core.simulate_dppm(my_dpp, W=window)
# Doing an envelope test using Ripley's K function.
Envelope = spatstat.core.envelope(rsample, spatstat.core.Kest, nsim=199)
# Plotting the result of the test.
base = robjects.packages.importr("base")
base.plot(Envelope)
```
The resulting plot is then
![2](https://user-images.githubusercontent.com/58079527/125358298-3faf1c80-e358-11eb-8677-4f8a5df23505.png)
which is definitely not what we want.

Could there be a way we can replicate with spatsat-interface the behaviour of the plot function applied to spatstat objects?

**Comment by guilgautier** [comment]
Hi @APoinas !

**Comment by guilgautier** [comment]
Hi @APoinas!
I have just activated the "Watch:All activity" and should now be warned when issues are raised 😅 

Regarding your problem, have you tried the [spatstat.core.plot.envelope](https://rdocumentation.org/packages/spatstat.core/versions/2.3-0/topics/plot.envelope) function ?

**Comment by APoinas** [comment]
No problem!
Unfortunately, when I try to call _spatstat.core.plot.envelope_ I get
`AttributeError: module 'spatstat.core' has no attribute 'plot'`

Moreover, the issue doesn't appear just for "envelope" type objects. For example, 
```
library(spatstat)

Kestim = Kest(rpoispp(100)) 
plot(Kestim)
```
in R gives
![c2cdf188-9d38-40da-ae86-2281b9a4ea3a](https://user-images.githubusercontent.com/58079527/136050508-59bdc21f-4b65-4c1f-934c-4f14210433c3.png)
while
```
import numpy as np
import pandas as pd

import rpy2.robjects as robjects
from rpy2.robjects import numpy2ri
numpy2ri.activate()

from spatstat_interface.interface import SpatstatInterface
from spatstat_interface.utils import convert_r_df_to_pandas_df

spatstat = SpatstatInterface(update=True)
spatstat.import_package("core", "geom", update=False)

Kestim = spatstat.core.Kest(spatstat.core.rpoispp(100))
base = robjects.packages.importr("base")
base.plot(Kestim)
```
in python gives
![Screenshot from 2021-10-05 17-06-19](https://user-images.githubusercontent.com/58079527/136050646-a51dd12e-89c3-40e1-9225-7263e4b1bdda.png)
Here, the plot function is applied to an object of class "fv".

As another example consider this R code simulating a DPP and plotting it:
```
library(spatstat)

rho0 = 100
alpha0 = 0.05
S_length = 2
S = simulate(dppBessel(lambda=rho0, alpha=alpha0, sigma=0, d=2), 1, W=owin(c(0,S_length), c(0,S_length)))
plot(S)
```
gives
![plot_zoom](https://user-images.githubusercontent.com/58079527/136051681-3102cbc3-d44e-4320-b969-bd2208130e59.png)
When trying to do the same in python:
```
import numpy as np
import pandas as pd

import rpy2.robjects as robjects
from rpy2.robjects import numpy2ri
numpy2ri.activate()

from spatstat_interface.interface import SpatstatInterface
from spatstat_interface.utils import convert_r_df_to_pandas_df

spatstat = SpatstatInterface(update=True)
spatstat.import_package("core", "geom", update=False)

rho = 100
alpha = 0.05
sigma = 0
d = 2
params = {"lambda": rho, "alpha": alpha, "sigma": sigma, "d": d}
my_dpp = spatstat.core.dppBessel(**params)
bound = robjects.FloatVector([0, 2])
window = spatstat.geom.owin(xrange=bound, yrange=bound)
rsample = spatstat.core.simulate_dppm(my_dpp, W=window)
base.plot(rsample)
```
we get
![Screenshot from 2021-10-05 17-12-58](https://user-images.githubusercontent.com/58079527/136052138-6f9f136a-9c03-4bdf-aad8-d9f3dd0c878c.png)
which is closer to the R output but still different. And in this case, the object we plot is of type "detpointprocfamily".

**Comment by guilgautier** [comment]
First let's compare what is comparable

## Initial code

### R code

```R
library(spatstat)
print(packageVersion("spatstat.core"))  # 2.3.0

rho = 100
alpha = 0.05
sigma = 0
d = 2

my_dpp = spatstat.core::dppBessel(lambda=rho, alpha=alpha, sigma=sigma, d=d)
bound = c(0, 2)
window = spatstat.geom::owin(xrange=bound, yrange=bound)
rsample = spatstat.core::simulate.dppm(my_dpp, W=window)
env = spatstat.core::envelope(rsample, spatstat.core::Kest, nsim=199)

spatstat.core::plot.envelope(env)
```

### Python code
```Python
import rpy2.robjects as robjects

from spatstat_interface.utils import convert_r_df_to_pandas_df
from spatstat_interface.interface import SpatstatInterface

spatstat = SpatstatInterface(update=True)
spatstat.import_package("core", "geom", update=True)
spatstat.core.__version__ # 2.3-0

rho = 100
alpha = 0.05
sigma = 0
d = 2

params = {"lambda": rho, "alpha": alpha, "sigma": sigma, "d": d}
my_dpp = spatstat.core.dppBessel(**params)
bound = robjects.FloatVector([0, 2])
window = spatstat.geom.owin(xrange=bound, yrange=bound)
rsample = spatstat.core.simulate_dppm(my_dpp, W=window)
env = spatstat.core.envelope(rsample, spatstat.core.Kest, nsim=199)

spatstat.core.plot_envelope(env)   # note the _ instead of the . in plot_envelope
```

--- 

In both cases I obtain

```bash
Error in NextMethod("plot", main = main) : 
  'NextMethod' called from an anonymous function
```

I find this very weird, but let's assume that's the normal behavior.

---

## Plotting 

### With R

```R
base::plot(env)
```

renders a nice plot as you posted above

### With Python

```python
base = robjects.packages.importr("base")
base.plot(env)
```

doesn't render any plot, but

```bash
R/rpy2 DataFrame (4 x 5)
lty	col	key	label	meaning
...	...	...	...	...
```

where
```python
env 
```

```
R/rpy2 DataFrame (513 x 5)
r | obs | theo | lo | hi
-- | -- | -- | -- | --
... | ... | ... | ... | ...
```




in a VSCode notebook. What is your IDE ?

**Comment by guilgautier** [comment]
More generally, I think the plotting has nothing to do with the spatstat-interface package as it is a very simple wrapper based on rpy2.
We should probably have a look at how rpy2 handles graphics, see, e.g., the [graphics section in rpy2's documentation](https://rpy2.github.io/doc/v3.4.x/html/graphics.html).

**Comment by guilgautier** [comment]
Nevertheless, one can simply use pandas.DataFrame as the Python counterpart of R DataFrame
Simply run the following, you should get something that looks similar to what you're looking for

```python
from spatstat_interface.utils import convert_r_df_to_pandas_df
df = convert_r_df_to_pandas_df(env)
df.plot(x="r")
```

**Comment by APoinas** [comment]
Yeah, it's pretty weird that we get different results. My IDE is Spyder so it could be IDE related.

I didn't know I could call plot.envelope in R by using plot_envelope with a _. Although, when I run your first python code in https://github.com/For-a-few-DPPs-more/spatstat-interface/issues/1#issuecomment-934592409 I get a different error message than you do:
`RRuntimeError: Error in verifyclass(X, "fv") : argument ‘X’ is not of class ‘fv’`
It's pretty weird.

**Comment by guilgautier** [comment]
> Although, when I run your first python code in [#1 (comment)](https://github.com/For-a-few-DPPs-more/spatstat-interface/issues/1#issuecomment-934592409) I get a different error message than you do: `RRuntimeError: Error in verifyclass(X, "fv") : argument ‘X’ is not of class ‘fv’` It's pretty weird.

The reason may be that you don't work with the latest version of the packages 

```R
# R
print(packageVersion("spatstat.core"))  # 2.3.0
```

```python
# Python
spatstat.core.__version__ # 2.3-0
```

> I didn't know I could call plot.envelope in R by using plot_envelope with a _. 

In R it's with a ., in Python using rpy2 it's a _

**Comment by APoinas** [comment]
You're right, it seems that I have the latest version of spatstat in R but not in Python where it's version 2.2.0 that is loaded. Using "update=true" when loading the packages in python doesn't seem to change it. Although, at least that explains the different outputs.

**Comment by APoinas** [comment]
After internal discussions, it seems that it's difficult to replicate the general behaviour of the plot function in R. Although, there seems to be some workaround.

Using spatstat.core.plot_fv(env) works for plotting envelopes;
Using spatstat.core.plot_fv(Kest) works for plotting Ripley's function estimates.

Also, the version of spatstat.core absolutely needs to be 2.3-0.
