### ISSUE TITLE
Creating a polygonal window in spatstat-interface

### ISSUE THREAD

**Issue by linmeixia** [For-a-few-DPPs-more/spatstat-interface#2]
In R, a polygonal window is created from the function "owin" with the input "poly" being a list or a matrix indicating the given vertices. While in spatstat-interface, how should we assign the input "poly"?  I have tried 'numpy.ndarray', 'dict', 'list', and 'rpy2.robjects.vectors.ListVector'. But none of them works.

**Comment by guilgautier** [comment]
Hi @linmeixia

It seems you managed to solve your issue. 
It would be great if you could post your solution to help future users.

Here's a suggestion
```python
import rpy2.robjects as ro
triangle = ro.DataFrame(
    {"x": ro.FloatVector([0, 1.5, 0]),
     "y": ro.FloatVector([0, 1.5, 3])}
)

from spatstat_interface.interface import SpatstatInterface
spatstat = SpatstatInterface()  
spatstat.import_package("geom")
polygon = spatstat.geom.owin(poly=triangle)
```

you can also give a try to `spatstat.geom.as_polygonal` https://rdrr.io/cran/spatstat.geom/man/as.polygonal.html

Feel free to raise issues, but please enclose a minimal example showing how you would do in R together with your Python trials.

More generally, spatstat-interface is nothing more than a simple Python interface based on [rpy2](https://rpy2.github.io/doc/latest/html/index.html) for convenient calls to spatstat packages as `spatat.geom.your_favorite_function`.
There are no special features "in" spatstat-interface.

**Comment by linmeixia** [comment]
Dear Guillaume,

Thanks a lot for the answer.

Best regards,
Meixia
