### ISSUE TITLE
How to install the subpackage 'model'?

### ISSUE THREAD

**Issue by linmeixia** [For-a-few-DPPs-more/spatstat-interface#5]
When I tried to install the subpackage 'model' in Jupyter Notebook as

from spatstat_interface.interface import SpatstatInterface    
spatstat = SpatstatInterface()
spatstat.import_package("core", "geom", "model", update=True)

It returns the error message:

ValueError: {'model'} are invalid spatstat subpackages ('core', 'data', 'geom', 'linnet', 'sparse', 'spatstat', 'utils') or extensions ('gui', 'Knet', 'local', 'sphere').

**Comment by guilgautier** [comment]
The new version of the package incorporates these changes.
Closing the issue for now.
Feel free to reopen it if needed.
